/* Actual browser inputs, normal clock, read-only state planning. Not human play.
Adapted from independent September20 critic harness; no simulation injection. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require(process.env.PW_PLAYWRIGHT||'C:/Users/jshun/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.resolve(process.env.PW_SHOTS||'node_modules/.cache/prism-warden/native');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!p.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(p,(e,d)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(d);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROME||'C:/Users/jshun/AppData/Local/ms-playwright/chromium-1155/chrome-win/chrome.exe'});const results=[];
async function play(mode){const touch=mode==='touch',page=await browser.newPage({viewport:touch?{width:390,height:844}:{width:1440,height:900},hasTouch:touch});const errs=[];page.on('pageerror',e=>errs.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/prism-warden/index.html`);await page.waitForFunction(()=>PW.game);await page.locator('#begin').click();const cdp=touch?await page.context().newCDPSession(page):null;let keys=new Set();
const get=()=>page.evaluate(()=>({time:PW.game.time,status:PW.game.status,player:PW.game.player,gate:PW.game.gates[0].open,sanctuary:PW.game.sanctuary,enemy:PW.game.enemies[0],hits:PW.game.hits,score:PW.game.score,returns:PW.game.returns}));
async function act(mx,my,aim,mirror,ms=80,slash=false,dash=false){const st=await get();if(touch){const move=await page.locator('#movePad').boundingBox(),mir=await page.locator('#mirrorPad').boundingBox();const center=b=>({x:b.x+b.width/2,y:b.y+b.height/2});const m=center(move),a=center(mir);const points=[];if(mx||my)points.push({id:1,...m});if(mirror)points.push({id:2,...a});if(slash||dash){const b=await page.locator(slash?'#slash':'#dash').boundingBox();points.push({id:3,...center(b)});}if(points.length){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});const len=Math.hypot(mx,my)||1,al=Math.hypot(aim[0]-st.player.x,aim[1]-st.player.y)||1;const moved=points.map(p=>p.id===1?{...p,x:p.x+mx/len*28,y:p.y+my/len*28}:p.id===2?{...p,x:p.x+(aim[0]-st.player.x)/al*28,y:p.y+(aim[1]-st.player.y)/al*28}:p);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:moved});}await page.waitForTimeout(ms);if(points.length)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{const want=new Set();if(mx<0)want.add('a');if(mx>0)want.add('d');if(my<0)want.add('w');if(my>0)want.add('s');if(mirror)want.add('Shift');for(const k of keys)if(!want.has(k))await page.keyboard.up(k);for(const k of want)if(!keys.has(k))await page.keyboard.down(k);keys=want;const coords=await page.evaluate(([x,y])=>{const r=document.getElementById('scene').getBoundingClientRect(),v=PW.view(PW.game,r.width,r.height);const p=PW.game.player;let sx=(x-v.x)*v.scale,sy=(y-v.y)*v.scale;const px=(p.x-v.x)*v.scale,py=(p.y-v.y)*v.scale;let t=1;if(sx<1)t=Math.min(t,(1-px)/(sx-px));if(sx>r.width-1)t=Math.min(t,(r.width-1-px)/(sx-px));if(sy<1)t=Math.min(t,(1-py)/(sy-py));if(sy>r.height-1)t=Math.min(t,(r.height-1-py)/(sy-py));return{x:r.left+px+(sx-px)*t,y:r.top+py+(sy-py)*t};},aim);await page.mouse.move(coords.x,coords.y);if(slash)await page.keyboard.press('j');if(dash)await page.keyboard.press('Space');await page.waitForTimeout(ms);}}
async function go(x,y,mirror=false,aim=[845,245]){let n=0;while(n++<180){const st=await get();if(st.status==='won')return;if(st.status!=='playing')throw Error('route ended '+JSON.stringify(st));const dx=x-st.player.x,dy=y-st.player.y;if(Math.hypot(dx,dy)<6){await act(0,0,aim,mirror,40);return;}await act(Math.abs(dx)>4?Math.sign(dx):0,Math.abs(dy)>4?Math.sign(dy):0,aim,mirror,Math.min(70,Math.max(22,Math.hypot(dx,dy)/190*500)));}throw Error('waypoint blocked '+x+','+y+' '+JSON.stringify(await get()));}
console.log(mode+' begin');
await page.waitForTimeout(2000);const idle=await get();await page.screenshot({path:path.join(out,mode+'-opening.png')});
await go(190,340);await go(280,340);await act(0,0,[280,620],true,1500);console.log(mode+' sanctuary',JSON.stringify(await get()));
await go(550,340);await act(0,0,[550,115],true,1500);await page.screenshot({path:path.join(out,mode+'-gate.png')});
await go(650,300);await go(750,300);await go(760,245);const combatStart=await get();
if(mode==='mirror-baseline'){for(let i=0;i<180;i++){const st=await get();if(st.status!=='playing'||st.enemy.hp<=0)break;await act(0,0,[st.enemy.x,st.enemy.y],true,100);}await page.screenshot({path:path.join(out,mode+'-outcome.png')});results.push({mode,idle,combatStart,outcome:await get(),errs});await page.close();return;}
let recovery=null;if(mode==='recovery'){for(let i=0;i<70;i++){if((await get()).player.hp<6)break;await act(0,0,[0,245],false,80);}const damaged=await get();await go(630,245);await go(630,340);await go(280,340);await go(280,620);await act(0,0,[845,245],false,2300);recovery={damaged,healed:await get()};console.log('recovery '+JSON.stringify(recovery));await page.screenshot({path:path.join(out,'recovery-healed.png')});await go(280,340);await go(630,340);await go(630,245);await go(750,245);}let dodgeVec=null;let count=0;while(count++<500){const st=await get();if(st.status!=='playing'||st.enemy.hp<=0)break;const dx=st.enemy.x-st.player.x,dy=st.enemy.y-st.player.y,dist=Math.hypot(dx,dy);let mx=0,my=0,mirror=true,slash=false,dash=false;
if(st.enemy.exposed>0){if(dist>62){mx=Math.abs(dx)>5?Math.sign(dx):0;my=Math.abs(dy)>5?Math.sign(dy):0;mirror=false;}else{slash=st.player.slashCooldown<=0;}}
else if(/lunge|charge/.test(st.enemy.phase)){if(!dodgeVec){let vx=-st.enemy.aimY,vy=st.enemy.aimX;const clearance=await page.evaluate(([vx,vy])=>{const s=PW.game,p=s.player,w=s.walls.concat(s.gates.filter(g=>!g.open)).map(r=>({x:r.x-18,y:r.y-18,w:r.w+36,h:r.h+36}));return[PW.raySegment(p.x,p.y,vx,vy,w,240).distance,PW.raySegment(p.x,p.y,-vx,-vy,w,240).distance];},[vx,vy]);if(clearance[1]>clearance[0]){vx=-vx;vy=-vy;}dodgeVec=[vx,vy];}mx=Math.abs(dodgeVec[0])>.25?Math.sign(dodgeVec[0]):0;my=Math.abs(dodgeVec[1])>.25?Math.sign(dodgeVec[1]):0;mirror=false;dash=st.player.dashCooldown<=0&&st.enemy.phase==='lunge';}
else if(dist<75){mx=Math.abs(dx)>8?-Math.sign(dx):0;my=Math.abs(dy)>8?-Math.sign(dy):0;mirror=true;}
if(!/lunge|charge/.test(st.enemy.phase))dodgeVec=null;await act(mx,my,[st.enemy.x,st.enemy.y],mirror,70,slash,dash);
}
await act(0,0,[914,150],false,40);await page.screenshot({path:path.join(out,mode+'-combat.png')});if((await get()).enemy.hp<=0){await go(914,170);await page.waitForTimeout(300);}await page.waitForTimeout(500);const ui=await page.evaluate(()=>['begin','scoreForm','scopeNote'].map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect(),c=getComputedStyle(e);return{id,hidden:e.hidden,display:c.display,visibility:c.visibility,opacity:c.opacity,rect:{x:r.x,y:r.y,w:r.width,h:r.height}}}));console.log('result UI '+JSON.stringify(ui));await page.screenshot({path:path.join(out,mode+'-results.png')});if((await get()).status!=='won')throw Error('Native route did not win: '+JSON.stringify(await get()));if(errs.length)throw Error(errs.join('; '));results.push({mode,idle,combatStart,recovery,outcome:await get(),errs});console.log(mode+' end '+JSON.stringify(results.at(-1)));await page.close();}
try{for(const mode of (process.argv[2]||'keyboard,mirror-baseline,touch').split(',')){try{await play(mode);}catch(e){results.push({mode,error:e.stack});process.exitCode=1;console.error(e);}}}finally{fs.writeFileSync(path.join(out,'play-report-'+(process.argv[2]||'all')+'.json'),JSON.stringify(results,null,2));await browser.close();}}main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());

