'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PW_PLAYWRIGHT||(process.platform==='win32'?'C:/Users/jshun/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright':'/opt/node22/lib/node_modules/playwright'));
const root=path.resolve(__dirname,'../..'),output=path.resolve(process.env.PW_SHOTS||'node_modules/.cache/prism-warden/smoke');
const sizes=(process.env.PW_VIEWPORTS||'320x568,390x844,844x390,768x1024,1440x900,3840x2160').split(',').map(s=>s.split('x').map(Number));
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);});});
async function main(){fs.mkdirSync(output,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report=[];try{browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROME||(process.platform==='win32'?'C:/Users/jshun/AppData/Local/ms-playwright/chromium-1155/chrome-win/chrome.exe':'/opt/pw-browsers/chromium-1194/chrome-linux/chrome')});for(const [width,height]of sizes){const touch=width<1000,page=await browser.newPage({viewport:{width,height},hasTouch:touch});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:'))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/prism-warden/index.html`);await page.waitForFunction(()=>window.PW?.game);await page.screenshot({path:path.join(output,`${width}x${height}-ready.png`)});await page.locator('#begin').click();await page.waitForFunction(()=>PW.game.time>.5);const before=await page.evaluate(()=>PW.game.player.x);await page.keyboard.down('d');await page.waitForFunction(()=>PW.game.time>.8);await page.waitForTimeout(250);await page.keyboard.up('d');assert(await page.evaluate(x=>PW.game.player.x>x,before),'keyboard moves');
if(touch){const cdp=await page.context().newCDPSession(page),move=await page.locator('#movePad').boundingBox(),mirror=await page.locator('#mirrorPad').boundingBox();let points=[{id:1,x:move.x+move.width/2,y:move.y+move.height/2},{id:2,x:mirror.x+mirror.width/2,y:mirror.y+mirror.height/2}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});points=points.map(p=>({...p,x:p.x+22}));const x=await page.evaluate(()=>PW.game.player.x);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points});await page.waitForTimeout(240);assert(await page.evaluate(x=>PW.game.player.reflecting&&PW.game.player.x>x,x),'simultaneous touch move/mirror');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(90);assert(await page.evaluate(()=>!PW.game.player.reflecting),'touch releases');for(const sel of ['#movePad','#mirrorPad','#slash','#dash']){const b=await page.locator(sel).boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=width+1&&b.y+b.height<=height+1,sel+' visible');assert(b.width>=44&&b.height>=44,sel+' 44px target');}}
await page.screenshot({path:path.join(output,`${width}x${height}-playing.png`)});assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'no horizontal overflow');await page.locator('#pause').click();const time=await page.evaluate(()=>PW.game.time);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>PW.game.time),time,'pause freezes');await page.locator('#begin').click();
// Explicit optical/guardian layout fixtures; these do NOT establish legal play.
await page.evaluate(()=>{const s=PW.game;s.player.x=550;s.player.y=340;s.shots=[];s.enemies.filter(e=>e.type==='turret').forEach(e=>{e.phase='jammed';e.timer=30;});});await page.keyboard.down('Shift');const aim=await page.evaluate(()=>{const r=document.getElementById('scene').getBoundingClientRect(),v=PW.view(PW.game,r.width,r.height);return{x:r.x+(550-v.x)*v.scale,y:Math.max(r.y+4,r.y+(115-v.y)*v.scale)};});await page.mouse.move(aim.x,aim.y);await page.waitForTimeout(1500);await page.keyboard.up('Shift');assert(await page.evaluate(()=>PW.game.gates[0].open),'actual aim charges receiver');await page.screenshot({path:path.join(output,`${width}x${height}-gate.png`)});
await page.evaluate(()=>{const s=PW.game,e=s.enemies[0];s.player.x=790;s.player.y=310;e.phase='lunge-windup';e.timer=.7;e.aimX=-.7;e.aimY=.7;});await page.waitForTimeout(80);await page.screenshot({path:path.join(output,`${width}x${height}-guardian.png`)});
// Declared room fixtures: enter each authored room and capture it (layout/visual evidence only).
for(const room of ['sluice','sanctuary','shutters','bell-tower','beacon']){await page.evaluate(r=>PW.enterRoom(PW.game,r),room);await page.waitForTimeout(1400);assert.equal(await page.evaluate(()=>PW.game.roomId),room);await page.screenshot({path:path.join(output,`${width}x${height}-${room}.png`)});}
// Loss -> Retry room restores the room entry snapshot.
await page.evaluate(()=>{PW.game.player.hp=1;PW.game.player.invulnerable=0;PW.game.player.dashTime=0;PW.game.shots.push({id:999,x:PW.game.player.x+20,y:PW.game.player.y,vx:-300,vy:0,friendly:false,life:3,r:7});});await page.waitForFunction(()=>PW.game.status==='lost');await page.waitForTimeout(400);assert(await page.locator('#begin').isVisible(),'retry visible');await page.screenshot({path:path.join(output,`${width}x${height}-lost.png`)});await page.locator('#begin').click();assert(await page.evaluate(()=>PW.game.status==='playing'&&PW.game.roomId==='beacon'&&PW.game.player.hp>1),'retry room restores');
await page.evaluate(()=>{const s=PW.game;s.enemies.forEach(e=>{e.hp=0;e.phase='defeated';e.submerged=false;});s.player.x=s.beacon.x;s.player.y=s.beacon.y+30;});await page.waitForFunction(()=>PW.game.status==='cleared');await page.waitForTimeout(500);await page.screenshot({path:path.join(output,`${width}x${height}-cleared.png`)});const calls=[];await page.route('**/api/leaderboard/**',async route=>{calls.push({url:route.request().url(),method:route.request().method(),body:route.request().postDataJSON()});await route.fulfill({status:200,contentType:'application/json',body:'{"rank":7}'});});await page.locator('#callsign').fill('PRISM TEST');await page.locator('#scoreForm button').click();await page.waitForFunction(()=>document.querySelector('#scoreStatus').textContent.includes('Rank #7'));assert.equal(calls.length,2);assert(calls[0].url.includes('gameId=prism-warden'));assert.equal(calls[1].body.gameId,'prism-warden');assert.equal(calls[1].method,'POST');await page.locator('#begin').click();assert(await page.evaluate(()=>PW.game.status==='playing'&&PW.game.roomId==='spillway'&&PW.game.regionId==='verdant-aqueduct'),'continue enters the aqueduct');
// Declared Region 2 room fixtures (layout/visual evidence only; legal play is tools/aqueduct-pilot.cjs).
for(const room of ['spillway','roots','channels','quay','ferry','reservoir']){await page.evaluate(r=>PW.enterRoom(PW.game,r),room);await page.waitForTimeout(1400);assert.equal(await page.evaluate(()=>PW.game.status),'playing');await page.screenshot({path:path.join(output,`${width}x${height}-${room}.png`)});}
await page.evaluate(()=>{const s=PW.game;s.player.invulnerable=99;s.enemies.forEach(e=>{e.hp=0;e.phase='defeated';});s.player.x=s.beacon.x;s.player.y=s.beacon.y+30;});await page.waitForFunction(()=>PW.game.status==='won');await page.waitForTimeout(500);await page.screenshot({path:path.join(output,`${width}x${height}-result.png`)});
await page.locator('#begin').click();assert(await page.evaluate(()=>PW.game.score===0&&PW.game.roomId==='cloister'&&!PW.game.gates[0].open&&PW.game.player.hp===PW.game.player.maxHp),'replay resets');
assert.deepEqual(errors,[],'console clean');assert.deepEqual(external,[],'no external runtime requests');report.push({width,height,errors,external,status:'PASS',touch});await page.close();}fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser?.close();server.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
