'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.IW_PLAYWRIGHT||'C:/Users/jshun/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),output=path.resolve(process.env.IW_SHOTS||'node_modules/.cache/ironwake/smoke');
const sizes=(process.env.IW_VIEWPORTS||'320x568,390x844,844x390,768x1024,1440x900,3840x2160').split(',').map(s=>s.split('x').map(Number));
const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(data);});});
async function main(){fs.mkdirSync(output,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.IW_CHROME||'C:/Users/jshun/AppData/Local/ms-playwright/chromium-1155/chrome-win/chrome.exe'});const report=[];try{
 for(const [width,height]of sizes){const page=await browser.newPage({viewport:{width,height},hasTouch:width<1000});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:'))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/ironwake/index.html`);await page.waitForFunction(()=>window.IW?.runtime);await page.screenshot({path:path.join(output,`${width}x${height}-ready.png`)});await page.locator('#start').click();
 // Opening aimed punch is actual keyboard input, at normal clock/state.
 await page.keyboard.press('e');await page.waitForFunction(()=>IW.runtime.state.collapseKills>0,{},{timeout:12000});await page.screenshot({path:path.join(output,`${width}x${height}-collapse.png`)});
 const before=await page.evaluate(()=>IW.runtime.state.player.x);await page.keyboard.down('d');await page.waitForTimeout(250);await page.keyboard.up('d');assert(await page.evaluate(x=>IW.runtime.state.player.x>x,before),'keyboard moves');
 if(width<1000){const cdp=await page.context().newCDPSession(page);const stick=await page.locator('#stick').boundingBox(),fire=await page.locator('[data-action=fire]').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:stick.x+stick.width*.8,y:stick.y+stick.height/2},{id:2,x:fire.x+fire.width/2,y:fire.y+fire.height/2}]});await page.waitForTimeout(200);assert(await page.evaluate(()=>IW.runtime.input.moveX>0&&IW.runtime.input.fire),'simultaneous touch moves and fires');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(70);assert(await page.evaluate(()=>!IW.runtime.input.fire&&IW.runtime.input.moveX===0),'touch releases');}
 await page.screenshot({path:path.join(output,`${width}x${height}-playing.png`)});assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth),'no horizontal overflow');
 for(const sel of ['[data-action=fire]','[data-action=punch]','[data-action=rip]','[data-action=vent]','[data-action=dash]','[data-action=interact]']){const r=await page.locator(sel).boundingBox();assert(r.height>=44&&r.y+r.height<=height+1,sel+' visible control');}
 // Overheat layout fixture, separate from normal-input opening combat.
 await page.evaluate(()=>{IW.runtime.state.player.heat=100;IW.runtime.state.player.overheated=true;});await page.waitForFunction(()=>document.querySelector('#heat').textContent==='HOT');assert(await page.locator('#heat').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.parentElement.getBoundingClientRect();return a.right<=b.right&&a.left>=b.left;}),'overheat fits HUD');await page.screenshot({path:path.join(output,`${width}x${height}-hot.png`)});
 // Defeat fixture verifies results/restart/API, not normal-run completion.
 await page.evaluate(()=>IW.runtime.state.player.hp=0);await page.waitForFunction(()=>IW.runtime.state.status==='lost');await page.screenshot({path:path.join(output,`${width}x${height}-results.png`)});for(const selector of ['#results','#callsign','#scoreForm button','#retry']){const b=await page.locator(selector).boundingBox();assert(b.x>=0&&b.x+b.width<=width+1,selector+' fits viewport width');}const retry=await page.locator('#retry').boundingBox();await page.locator('#retry').scrollIntoViewIfNeeded();
 const calls=[];await page.route('**/api/leaderboard/**',async route=>{calls.push({url:route.request().url(),method:route.request().method()});await route.fulfill({status:200,contentType:'application/json',body:'{"rank":7}'});});await page.locator('#callsign').fill('IRON TEST');await page.locator('#scoreForm button').click();await page.waitForFunction(()=>document.querySelector('#scoreStatus').textContent.includes('RANK #7'));assert(calls[0].url.includes('/rank?gameId=ironwake'));assert.equal(calls[1].method,'POST');await page.locator('#retry').click();assert(await page.evaluate(()=>IW.runtime.state.player.weapon==='cannon'&&IW.runtime.state.score===0),'retry resets');await page.locator('#mapButton').click();const pausedTime=await page.evaluate(()=>IW.runtime.state.time);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>IW.runtime.state.time),pausedTime,'map pauses simulation');await page.screenshot({path:path.join(output,width+'x'+height+'-map.png')});await page.locator('#resume').click();
 // End-of-chapter fixture exercises actual objective completion and persistent upgrade UI.
 await page.evaluate(()=>{const s=IW.runtime.state;s.stage=3;s.objectives.slice(0,3).forEach(o=>o.done=true);s.player.x=s.objectives[3].x;s.player.z=s.objectives[3].z;});await page.waitForFunction(()=>IW.runtime.state.status==='won');await page.screenshot({path:path.join(output,width+'x'+height+'-upgrade.png')});await page.locator('[data-upgrade=armor]').click();assert(await page.evaluate(()=>IW.runtime.state.chapter===1&&IW.runtime.state.upgrades.armor===1),'chapter upgrade advances');await page.reload();await page.waitForFunction(()=>IW.runtime?.state.chapter===1);await page.locator('#start').click();assert(await page.evaluate(()=>IW.runtime.state.player.maxHp===290),'saved module applies');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);report.push({width,height,collapse:true,input:true,results:true,leaderboard:true,errors});await page.close();
 }
 }finally{await browser.close();}fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
