const fs=require('fs'),vm=require('vm'),path=require('path');
const ctx={console};vm.createContext(ctx);for(const f of ['logic','campaign'])vm.runInContext(fs.readFileSync(path.join(__dirname,`../ironwake/assets/js/${f}.js`),'utf8'),ctx);const IW=ctx.IW;
function game(chapter=0){const s=IW.createCampaignState(chapter);IW.start(s);return s;}
function run(s,input,seconds){for(let i=0;i<seconds*60;i++)IW.step(s,input,1/60);}
describe('Ironwake coast campaign',()=>{
  test('five distinct large environments contain twenty ordered objectives, pressure profiles and optional discoveries',()=>{expect(new Set(IW.CAMPAIGN.map(c=>c.biome)).size).toBe(5);expect(new Set(IW.CAMPAIGN.map(c=>c.pressure.label)).size).toBe(5);expect(IW.CAMPAIGN.reduce((n,c)=>n+c.stages.length,0)).toBe(20);for(let i=0;i<5;i++){const s=game(i);expect(s.bounds.maxX-s.bounds.minX).toBeGreaterThanOrEqual(200);expect(s.enemies.length).toBeGreaterThan(10);expect(s.pickups.some(c=>c.type==='intel')).toBe(true);expect(s.buildings.some(b=>IW.inFootprint(s.player,b,1.1,0))).toBe(false);for(const o of s.objectives)expect(s.buildings.some(b=>IW.inFootprint(o,b,1.1,0))).toBe(false);}});
 test('campaign simulation is deterministic and has no arbitrary expiry',()=>{const a=game(),b=game();run(a,{moveX:-1},3);run(b,{moveX:-1},3);expect(a).toEqual(b);expect(a.status).toBe('playing');expect(a.timeLeft).toBe(0);});
 test('opening tower crush works through campaign simulation',()=>{const s=game();IW.step(s,{punch:true,aimX:-65,aimZ:40},1/60);run(s,{},2.1);expect(s.collapseKills).toBeGreaterThanOrEqual(1);expect(s.stage).toBe(0);});
 test('boost moves quickly, respects solid walls and has a cooldown',()=>{const s=game();s.enemies=[];const x=s.player.x;run(s,{moveX:1,dash:true},.3);expect(s.player.x-x).toBeGreaterThan(8);expect(s.player.dashCooldown).toBeGreaterThan(3);const p=s.player;p.x=-65;p.z=65;run(s,{moveZ:-1,dash:true},.5);expect(p.z).toBeGreaterThan(60);});
 test('captures require proximity, interaction and a clear perimeter',()=>{const s=game();s.stage=1;const o=s.objectives[1];s.player.x=o.x;s.player.z=o.z;run(s,{interact:true},1);expect(o.progress).toBe(0);s.enemies=s.enemies.filter(e=>Math.hypot(e.x-o.x,e.z-o.z)>25);run(s,{},1);expect(o.progress).toBe(0);run(s,{interact:true},7.1);expect(s.stage).toBe(2);expect(o.done).toBe(true);});
 test('artillery warns before damaging and can be dodged',()=>{const s=game(2);s.buildings=[];s.enemies=s.enemies.filter(e=>e.type==='artillery').slice(0,1);const e=s.enemies[0];e.x=s.player.x;e.z=s.player.z-20;e.cooldown=0;IW.step(s,{},.05);expect(s.strikes).toHaveLength(1);expect(s.player.hp).toBe(s.player.maxHp);run(s,{moveX:1,dash:true},2);expect(s.player.hp).toBe(s.player.maxHp);});
 test('an artillery impact damages an exposed stationary mech',()=>{const s=game(2);s.buildings=[];s.enemies=[];s.strikes=[{id:1,x:s.player.x,z:s.player.z,radius:6,life:.1,maxLife:1.6,damage:24}];run(s,{},.2);expect(s.player.hp).toBe(216);});
 test('water cools and slows while furnace vents damage armor',()=>{const wet=game(1),dry=game(1);for(const s of [wet,dry]){s.enemies=[];s.buildings=[];s.player.heat=80;s.player.x=0;s.player.z=0;}wet.hazards=[{x:0,z:0,radius:30,type:'water'}];dry.hazards=[];run(wet,{moveX:1},1);run(dry,{moveX:1},1);expect(wet.player.x).toBeLessThan(dry.player.x);expect(wet.player.heat).toBeLessThan(dry.player.heat);wet.hazards=[{x:0,z:0,radius:30,type:'fire'}];run(wet,{},1);expect(wet.player.hp).toBeLessThan(wet.player.maxHp);});
  test('repair and archive caches trigger once',()=>{const s=game();const cache=s.pickups.find(c=>c.type==='repair');s.player.hp=80;Object.assign(s.player,{x:cache.x,z:cache.z});run(s,{},.1);expect(s.player.hp).toBe(180);run(s,{},.1);expect(s.player.hp).toBe(180);const intel=s.pickups.find(c=>c.type==='intel');Object.assign(s.player,{x:intel.x,z:intel.z});run(s,{},.1);expect(s.totals.intel).toHaveLength(1);expect(s.radio).toContain('ARCHIVE');});
  test('chapter pressure changes enemy behavior and nearby caches announce their reward',()=>{const tide=game(1),guns=game(2);expect(tide.enemies.find(e=>e.type==='hunter').hunterSpeed).toBeGreaterThan(guns.enemies.find(e=>e.type==='hunter').hunterSpeed);expect(guns.enemies.find(e=>e.type==='artillery').artilleryRadius).toBeGreaterThan(tide.enemies.find(e=>e.type==='artillery').artilleryRadius);const s=game();s.enemies=[];const intel=s.pickups.find(c=>c.type==='intel');Object.assign(s.player,{x:intel.x,z:intel.z+12});run(s,{},.05);expect(s.context).toMatch(/^ARCHIVE SIGNAL/);});
 test('defense uplink pauses outside its radius and sends three counterattacks',()=>{const s=game(3);s.enemies=s.enemies.filter(e=>e.z< -60);s.stage=2;const o=s.objectives[2];run(s,{},1);expect(o.progress).toBe(0);Object.assign(s.player,{x:o.x,z:o.z});for(let i=0;i<40*60+2;i++){s.player.hp=s.player.maxHp;IW.step(s,{},1/60);}expect(s.stage).toBe(3);expect(s.wave).toBe(3);expect(s.enemies.filter(e=>e.id.startsWith('wave-'))).toHaveLength(9);});
 test('boss stays locked until both approaches clear, then exposes its core and changes phases',()=>{const s=game(4),boss=s.enemies.find(e=>e.type==='boss');s.buildings=[];s.player.x=0;s.player.z=-50;run(s,{fire:true,aimX:0,aimZ:-65},.7);expect(boss.hp).toBe(boss.maxHp);s.stage=2;s.player.heat=0;s.time=9;s.strikes=[];boss.cooldown=0;for(let i=0;i<60;i++)IW.step(s,{fire:true,aimX:boss.x,aimZ:boss.z},1/60);expect(s.strikes).toHaveLength(0);expect(boss.exposed).toBe(true);expect(boss.hp).toBeLessThan(boss.maxHp);boss.hp=500;IW.step(s,{},.05);expect(boss.phase).toBe(2);});
 test('upgrades require victory; checkpoint reload and retry preserve chapter and installed modules',()=>{const s=game();expect(IW.advance(s,'armor')).toBe(false);s.status='won';s.score=4500;expect(IW.advance(s,'armor')).toBe(true);expect(s.chapter).toBe(1);expect(s.player.maxHp).toBe(290);const restored=IW.restoreCampaign(JSON.parse(JSON.stringify(IW.campaignSave(s))));expect(restored.chapter).toBe(1);expect(restored.score).toBe(4500);IW.start(restored);restored.score=9000;restored.status='lost';IW.start(restored);expect(restored.score).toBe(4500);expect(restored.player.hp).toBe(290);});
 test('completed debrief survives reload without losing upgrade choice or duplicating rewards',()=>{const s=game();s.status='won';s.score=6000;s.kills=10;const restored=IW.restoreCampaign(JSON.parse(JSON.stringify(IW.campaignSave(s))));expect(restored.status).toBe('won');expect(restored.score).toBe(6000);IW.advance(restored,'reactor');expect(restored.chapter).toBe(1);expect(restored.score).toBe(6000);expect(restored.upgrades.reactor).toBe(1);});
 test('invalid saves safely reset and final chapter cannot overflow campaign',()=>{expect(IW.restoreCampaign({version:1,chapter:99}).chapter).toBe(0);const s=game(4);s.status='won';expect(IW.advance(s,'damage')).toBe(false);});
 test('luring an assigned defender out of its sector does not complete elimination',()=>{const s=game(),ids=s.objectives[0].targets;s.enemies.filter(e=>ids.includes(e.id)).forEach(e=>{e.x=90;e.z=90;});run(s,{},.1);expect(s.stage).toBe(0);});
 test('lethal furnace damage cannot be undone by a pickup or extraction in the same frame',()=>{const s=game();s.stage=3;const o=s.objectives[3];Object.assign(s.player,{x:o.x,z:o.z,hp:.01});s.hazards=[{x:o.x,z:o.z,type:'fire',radius:10}];s.pickups=[{id:'repair',x:o.x,z:o.z,type:'repair',taken:false}];IW.step(s,{},.05);expect(s.status).toBe('lost');expect(s.player.hp).toBe(0);});
});
