'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
function load(){const context={window:{},Math,Number};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../prism-warden/assets/js/regions.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../prism-warden/assets/js/logic.js'),'utf8'),context);return context.window.PW;}
let PW,s;beforeEach(()=>{PW=load();s=PW.create();s.status='playing';});
function steps(input,n=60){for(let i=0;i<n;i++)PW.step(s,input,1/60);}
function at(x,y){s.player.x=x;s.player.y=y;}
function open(){s.gates[0].open=true;s.receivers[0].active=true;}
function shot(x,y,vx,vy){s.shots.push({id:9,x,y,vx,vy,friendly:false,life:4,r:7});}
test('campaign map has five connected regions and twenty-five authored challenges',()=>{expect(PW.REGIONS).toHaveLength(5);const challenges=PW.REGIONS.flatMap(region=>region.challenges);expect(challenges).toHaveLength(25);expect(new Set(challenges.map(challenge=>challenge.id)).size).toBe(25);expect(challenges.map(challenge=>challenge.id)).toEqual(['A1','A2','A3','A4','A5','B1','B2','B3','B4','B5','C1','C2','C3','C4','C5','D1','D2','D3','D4','D5','E1','E2','E3','E4','E5']);for(const region of PW.REGIONS){const graph=PW.routeGraph(region.id),seen=new Set([region.rooms[0].id]),queue=[region.rooms[0].id];while(queue.length){for(const next of graph[queue.shift()])if(!seen.has(next)){seen.add(next);queue.push(next);}}expect(seen.size).toBe(region.rooms.length);}expect(PW.regionById('tidal-abbey').challenges[0].title).toBe('Sun Under Fire');expect(PW.challengeById('E5').guardian).toBe('Eclipse Keeper');expect(PW.FIRST_PLAYABLE.regionId).toBe('tidal-abbey');expect(PW.campaignContract()).toEqual({regions:5,challenges:25,firstPlayable:'courtyard-checkpoint',complete:false});});
test('fresh state independent and no idle victory or passive points',()=>{const other=PW.create();steps({},3600);expect(s.status).toBe('lost');expect(s.score).toBe(0);expect(other.time).toBe(0);expect(s.rescue.freed).toBe(false);expect(s.roomId).toBe('cloister');});
test('slab ray handles parallel, blocked, open and inside origins',()=>{const box={x:100,y:100,w:20,h:50};expect(PW.raySegment(0,120,1,0,[box],500).distance).toBe(100);expect(PW.raySegment(0,90,1,0,[box],500).distance).toBe(500);expect(PW.raySegment(110,120,1,0,[box],500).distance).toBe(0);expect(PW.raySegment(0,120,1,0,[{...box,open:true}],500).distance).toBe(500);});
test('normalizes diagonal movement and prevents dash tunnelling through locked gate',()=>{at(600,180);steps({mx:1,my:1},10);const dist=Math.hypot(s.player.x-600,s.player.y-180);expect(dist).toBeCloseTo(190/6,5);at(680,180);steps({mx:1,ax:1,dash:true},30);expect(s.player.x).toBeLessThanOrEqual(686.01);expect(s.player.dashCooldown).toBeGreaterThan(0);});
test('sun receiver requires mirror plus aimed continuous charge; opens once',()=>{at(550,340);steps({ax:0,ay:-1},90);expect(s.gates[0].open).toBe(false);steps({reflect:true,ax:0,ay:-1},35);expect(s.receivers[0].charge).toBeGreaterThan(.4);steps({ax:1,ay:0},50);expect(s.receivers[0].charge).toBe(0);steps({reflect:true,ax:0,ay:-1},80);expect(s.gates[0].open).toBe(true);const score=s.score;steps({reflect:true,ax:0,ay:-1},150);expect(s.score).toBe(score);});
test('cannot intercept beam through solid wall',()=>{at(800,340);steps({reflect:true,ax:-1,ay:-1},90);expect(s.beams).toHaveLength(1);expect(s.receivers[0].active).toBe(false);});
test('sanctuary is an optional healing circuit with one-time score',()=>{at(280,340);s.player.hp=2;steps({reflect:true,ax:0,ay:1},80);expect(s.sanctuary).toBe(true);expect(s.player.hp).toBe(s.player.maxHp);expect(s.gates[0].open).toBe(false);const score=s.score;steps({reflect:true,ax:0,ay:1},180);expect(s.score).toBe(score);});
test('front-facing shot returns while rear-facing mirror is hit',()=>{open();at(600,340);shot(640,340,-245,0);steps({reflect:true,ax:1,ay:0},3);expect(s.shots.some(p=>p.friendly)).toBe(true);s=PW.create();s.status='playing';open();at(600,340);shot(640,340,-245,0);steps({reflect:true,ax:-1,ay:0},8);expect(s.hits).toBe(1);});
test('hit grace prevents simultaneous projectiles draining all health',()=>{open();at(600,340);for(let i=0;i<6;i++)shot(628,340,-245,0);steps({ax:0,ay:1},8);expect(s.hits).toBe(1);expect(s.player.hp).toBe(s.player.maxHp-1);});
test('dash avoids a projectile and cannot immediately repeat',()=>{open();at(600,340);shot(635,340,-245,0);steps({my:-1,ax:1,dash:true},10);expect(s.hits).toBe(0);expect(s.player.dashCooldown).toBeGreaterThan(.8);const cd=s.player.dashCooldown;steps({dash:false},1);steps({dash:true},1);expect(s.player.dashCooldown).toBeLessThan(cd);});
test('closed gate and living guardian prevent rescue; rescue frees Ilex but does not end the region',()=>{s.enemies.find(e=>e.type==='turret').phase='silent';at(914,150);steps({},10);expect(s.rescue.freed).toBe(false);open();steps({},10);expect(s.rescue.freed).toBe(false);s.enemies[0].hp=0;steps({},1);expect(s.rescue.freed).toBe(true);expect(s.flags.ilex).toBe(true);expect(s.status).toBe('playing');const score=s.score;steps({},60);expect(s.score).toBe(score);});
test('sword cannot damage intact armor; exposed enemy takes one hit per swing',()=>{open();at(795,245);const e=s.enemies[0],hp=e.hp;steps({ax:1,slash:true},15);expect(e.hp).toBe(hp);steps({slash:false},30);e.exposed=3;e.phase='exposed';steps({ax:1,slash:true},10);expect(e.hp).toBe(hp-2);steps({ax:1,slash:true},50);expect(e.hp).toBe(hp-2);});
test('pause and terminal states do not tick; nonfinite dt ignored and large dt clamped',()=>{s.status='ready';steps({mx:1},60);expect(s.time).toBe(0);s.status='playing';PW.step(s,{},NaN);expect(s.time).toBe(0);PW.step(s,{},10);expect(s.time).toBeCloseTo(1/30,8);});
test('identical input streams replay deterministically',()=>{const a=PW.create(),b=PW.create();a.status=b.status='playing';for(let i=0;i<1000;i++){const input={mx:Math.sin(i*.01),my:Math.cos(i*.02),ax:Math.cos(i*.03),ay:Math.sin(i*.03),reflect:i%100<50,dash:i%131===0,slash:i%73===0};PW.step(a,input,1/60);PW.step(b,input,1/60);}expect(JSON.stringify(a)).toBe(JSON.stringify(b));});

test('a returned shot opens armor without damaging guardian health',()=>{open();at(760,245);const e=s.enemies[0],hp=e.hp;s.shots.push({id:1,x:810,y:245,vx:390,vy:0,friendly:true,life:3,r:7});steps({ax:1,reflect:true},3);expect(e.hp).toBe(hp);expect(e.exposed).toBeGreaterThan(3);expect(s.returns).toBe(1);});
test('passive shield cannot kill guardian and repeated openings do not farm score',()=>{open();at(760,245);for(let i=0;i<3600&&s.status==='playing';i++){const e=s.enemies[0];PW.step(s,{ax:e.x-s.player.x,ay:e.y-s.player.y,reflect:true},1/60);}expect(s.enemies[0].hp).toBe(s.enemies[0].maxHp);expect(s.status).toBe('lost');expect(s.score).toBeLessThanOrEqual(100);});
test('whole Tidal Abbey is solvable with legal inputs, deterministically, with and without the optional sanctuary',()=>{const {play,loadPW}=require('../prism-warden/tools/abbey-pilot.cjs');const a=play(loadPW()),b=play(loadPW());expect(a.status).toBe('won');expect(a.cleared).toEqual({A1:true,A2:true,A3:true,A4:true,A5:true});expect(a.flags.chart).toBe(true);expect(a.player.hp).toBeGreaterThan(0);expect(JSON.stringify(a)).toBe(JSON.stringify(b));const c=play(loadPW(),{sanctuary:false});expect(c.status).toBe('won');expect(c.flags.chart).toBeUndefined();},180000);
test('six connected rooms: every exit leads to a defined room and back',()=>{const ids=Object.keys(PW.ROOMS).sort();expect(ids).toEqual(['beacon','bell-tower','cloister','sanctuary','shutters','sluice']);for(const id of ids){const def=PW.roomDef(id);for(const ex of def.exits){expect(PW.ROOMS[ex.to]).toBeTruthy();expect(PW.roomDef(ex.to).exits.some(back=>back.to===id)).toBe(true);}}expect(PW.roomDef('nowhere')).toBeNull();});
test('room state persists across exits and re-entry never duplicates score',()=>{open();s.enemies.forEach(e=>{e.hp=0;e.phase=e.type==='turret'?'silent':'defeated';});PW.enterRoom(s,'sluice');expect(s.roomId).toBe('sluice');expect(s.visited).toContain('sluice');const score=s.score;PW.enterRoom(s,'cloister');expect(s.gates[0].open).toBe(true);expect(s.enemies[0].hp).toBe(0);expect(s.score).toBe(score);});
test('retry room restores the entry snapshot including score',()=>{PW.enterRoom(s,'sluice');const score=s.score,hp=s.player.hp;s.score+=999;s.player.hp=0;s.status='lost';PW.retryRoom(s);expect(s.status).toBe('playing');expect(s.score).toBe(score);expect(s.player.hp).toBe(hp);expect(s.roomId).toBe('sluice');});
test('bell tower needs both bells lit at once from the rotated mirrors',()=>{PW.enterRoom(s,'bell-tower');const v=s.enemies.find(e=>e.type==='sentinel');v.hp=0;v.phase='defeated';steps({},120);expect(s.gates.find(g=>g.id==='bell-gate').open).toBe(false);const want={'west-high':2,'east-high':1,'west-bell-mirror':2,'east-bell-mirror':1};for(const m of s.mirrors)if(m.id in want)m.index=want[m.id];steps({},150);expect(s.gates.find(g=>g.id==='bell-gate').open).toBe(true);expect(s.cleared.A4).toBe(true);});
test('tide floods water lanes and wading hurts; shutters and breakwaters never close on a body',()=>{PW.enterRoom(s,'sluice');let sawHigh=false,sawLow=false;for(let i=0;i<60*12;i++){PW.step(s,{},1/60);if(s.tide.high)sawHigh=true;else sawLow=true;if(s.status!=='playing')break;}expect(sawHigh&&sawLow).toBe(true);PW.enterRoom(s,'shutters');s.status='playing';const sh=s.shutters[0];at(sh.x+sh.w/2,sh.y+sh.h/2);s.enemies.forEach(e=>e.phase='silent');for(let i=0;i<60*8;i++){PW.step(s,{},1/60);if(s.status!=='playing')break;expect(sh.open||sh.held).toBeTruthy();}});
test('escort death loses the room',()=>{PW.enterRoom(s,'shutters');s.escort.hp=1;s.escort.invulnerable=0;s.shots.push({id:77,x:s.escort.x+30,y:s.escort.y,vx:-300,vy:0,friendly:false,life:3,r:7,owner:'x'});steps({},20);expect(s.escort.hp).toBe(0);expect(s.status).toBe('lost');});
