'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
function load(){const context={window:{},Math,Number};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../prism-warden/assets/js/regions.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../prism-warden/assets/js/logic.js'),'utf8'),context);return context.window.PW;}
let PW,s;beforeEach(()=>{PW=load();s=PW.create();s.status='playing';});
function steps(input,n=60){for(let i=0;i<n;i++)PW.step(s,input,1/60);}
function at(x,y){s.player.x=x;s.player.y=y;}
function open(){s.gates[0].open=true;s.receivers[0].active=true;}
function shot(x,y,vx,vy){s.shots.push({id:9,x,y,vx,vy,friendly:false,life:4,r:7});}
test('campaign map has five connected regions and twenty-five authored challenges',()=>{expect(PW.REGIONS).toHaveLength(5);const challenges=PW.REGIONS.flatMap(region=>region.challenges);expect(challenges).toHaveLength(25);expect(new Set(challenges.map(challenge=>challenge.id)).size).toBe(25);expect(challenges.map(challenge=>challenge.id)).toEqual(['A1','A2','A3','A4','A5','B1','B2','B3','B4','B5','C1','C2','C3','C4','C5','D1','D2','D3','D4','D5','E1','E2','E3','E4','E5']);expect(PW.regionById('tidal-abbey').challenges[0].title).toBe('Sun Under Fire');expect(PW.challengeById('E5').guardian).toBe('Eclipse Keeper');expect(PW.FIRST_PLAYABLE.regionId).toBe('tidal-abbey');expect(PW.campaignContract()).toEqual({regions:5,challenges:25,firstPlayable:'courtyard-checkpoint',complete:false});});
test('fresh state independent and no idle victory or passive points',()=>{const other=PW.create();steps({},3600);expect(s.status).toBe('playing');expect(s.score).toBe(0);expect(other.time).toBe(0);expect(s.rescue.freed).toBe(false);});
test('slab ray handles parallel, blocked, open and inside origins',()=>{const box={x:100,y:100,w:20,h:50};expect(PW.raySegment(0,120,1,0,[box],500).distance).toBe(100);expect(PW.raySegment(0,90,1,0,[box],500).distance).toBe(500);expect(PW.raySegment(110,120,1,0,[box],500).distance).toBe(0);expect(PW.raySegment(0,120,1,0,[{...box,open:true}],500).distance).toBe(500);});
test('normalizes diagonal movement and prevents dash tunnelling through locked gate',()=>{at(600,180);steps({mx:1,my:1},10);const dist=Math.hypot(s.player.x-600,s.player.y-180);expect(dist).toBeCloseTo(190/6,5);at(680,180);steps({mx:1,ax:1,dash:true},30);expect(s.player.x).toBeLessThanOrEqual(686.01);expect(s.player.dashCooldown).toBeGreaterThan(0);});
test('sun receiver requires mirror plus aimed continuous charge; opens once',()=>{at(550,340);steps({ax:0,ay:-1},90);expect(s.gates[0].open).toBe(false);steps({reflect:true,ax:0,ay:-1},35);expect(s.receivers[0].charge).toBeGreaterThan(.4);steps({ax:1,ay:0},50);expect(s.receivers[0].charge).toBe(0);steps({reflect:true,ax:0,ay:-1},80);expect(s.gates[0].open).toBe(true);const score=s.score;steps({reflect:true,ax:0,ay:-1},150);expect(s.score).toBe(score);});
test('cannot intercept beam through solid wall',()=>{at(800,340);steps({reflect:true,ax:-1,ay:-1},90);expect(s.beams).toHaveLength(1);expect(s.receivers[0].active).toBe(false);});
test('sanctuary is an optional healing circuit with one-time score',()=>{at(280,340);s.player.hp=2;steps({reflect:true,ax:0,ay:1},80);expect(s.sanctuary).toBe(true);expect(s.player.hp).toBe(s.player.maxHp);expect(s.gates[0].open).toBe(false);const score=s.score;steps({reflect:true,ax:0,ay:1},180);expect(s.score).toBe(score);});
test('front-facing shot returns while rear-facing mirror is hit',()=>{open();at(600,340);shot(640,340,-245,0);steps({reflect:true,ax:1,ay:0},3);expect(s.shots.some(p=>p.friendly)).toBe(true);s=PW.create();s.status='playing';open();at(600,340);shot(640,340,-245,0);steps({reflect:true,ax:-1,ay:0},8);expect(s.hits).toBe(1);});
test('hit grace prevents simultaneous projectiles draining all health',()=>{open();at(600,340);for(let i=0;i<6;i++)shot(628,340,-245,0);steps({ax:0,ay:1},8);expect(s.hits).toBe(1);expect(s.player.hp).toBe(s.player.maxHp-1);});
test('dash avoids a projectile and cannot immediately repeat',()=>{open();at(600,340);shot(635,340,-245,0);steps({my:-1,ax:1,dash:true},10);expect(s.hits).toBe(0);expect(s.player.dashCooldown).toBeGreaterThan(.8);const cd=s.player.dashCooldown;steps({dash:false},1);steps({dash:true},1);expect(s.player.dashCooldown).toBeLessThan(cd);});
test('closed gate and living guardian prevent rescue',()=>{at(914,150);steps({},10);expect(s.status).toBe('playing');expect(s.rescue.freed).toBe(false);open();steps({},10);expect(s.rescue.freed).toBe(false);s.enemies[0].hp=0;steps({},1);expect(s.rescue.freed).toBe(true);expect(s.status).toBe('won');const score=s.score;steps({},60);expect(s.score).toBe(score);});
test('sword cannot damage intact armor; exposed enemy takes one hit per swing',()=>{open();at(795,245);const e=s.enemies[0],hp=e.hp;steps({ax:1,slash:true},15);expect(e.hp).toBe(hp);steps({slash:false},30);e.exposed=3;e.phase='exposed';steps({ax:1,slash:true},10);expect(e.hp).toBe(hp-2);steps({ax:1,slash:true},50);expect(e.hp).toBe(hp-2);});
test('pause and terminal states do not tick; nonfinite dt ignored and large dt clamped',()=>{s.status='ready';steps({mx:1},60);expect(s.time).toBe(0);s.status='playing';PW.step(s,{},NaN);expect(s.time).toBe(0);PW.step(s,{},10);expect(s.time).toBeCloseTo(1/30,8);});
test('identical input streams replay deterministically',()=>{const a=PW.create(),b=PW.create();a.status=b.status='playing';for(let i=0;i<1000;i++){const input={mx:Math.sin(i*.01),my:Math.cos(i*.02),ax:Math.cos(i*.03),ay:Math.sin(i*.03),reflect:i%100<50,dash:i%131===0,slash:i%73===0};PW.step(a,input,1/60);PW.step(b,input,1/60);}expect(JSON.stringify(a)).toBe(JSON.stringify(b));});

test('a returned shot opens armor without damaging guardian health',()=>{open();at(760,245);const e=s.enemies[0],hp=e.hp;s.shots.push({id:1,x:810,y:245,vx:390,vy:0,friendly:true,life:3,r:7});steps({ax:1,reflect:true},3);expect(e.hp).toBe(hp);expect(e.exposed).toBeGreaterThan(3);expect(s.returns).toBe(1);});
test('passive shield cannot kill guardian and repeated openings do not farm score',()=>{open();at(760,245);for(let i=0;i<3600&&s.status==='playing';i++){const e=s.enemies[0];PW.step(s,{ax:e.x-s.player.x,ay:e.y-s.player.y,reflect:true},1/60);}expect(s.enemies[0].hp).toBe(s.enemies[0].maxHp);expect(s.status).toBe('lost');expect(s.score).toBeLessThanOrEqual(100);});
test('complete encounter is solvable twice using only legal inputs',()=>{const {winningRoute}=require('../prism-warden/tools/solvability.cjs');const a=winningRoute(PW),b=winningRoute(PW);expect(a.status).toBe('won');expect(a.sanctuary).toBe(true);expect(a.returns).toBe(3);expect(a.player.hp).toBeGreaterThan(0);expect(a.enemies[0].hp).toBe(0);expect(JSON.stringify(a)).toBe(JSON.stringify(b));});
